# global settings
global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: 
    - 'prometheus:9090'

- job_name: redis-exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'redis-exporter:9121'

- job_name: webapp
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'webapp:9000'
